version: '3.5'
services:
  mystrapi-dev:
    container_name: culture-portal-cusco-admin-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: culture-portal-cusco-admin-dev:${APP_VERSION}
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: mystrapiDB-dev
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV_DEV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1338:1337'
    networks:
      - mystrapi_network_dev
    depends_on:
      - mystrapiDBDev
      
  mystrapiDBDev:
    container_name: mystrapiDB-dev
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      # - mystrapi-data:/var/lib/postgresql/data/ #using a volume
      - /var/lib/postgresql/dev/data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5433:5432'
    networks:
      - mystrapi_network_dev
      
  # mystrapiAdminer:
  #   container_name: mystrapiAdminer
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - '9090:8080'
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=mystrapiDB
  #   networks:
  #     - mystrapi
  #   depends_on:
  #     - mystrapiDB

volumes:
  mystrapi-data:

networks:
  mystrapi_network_dev:
    name: Mystrapi-dev
    driver: bridge
