name: Add Strapi content type from dev to main

on:
  workflow_dispatch


jobs:
  get-strapi-content-type:
    runs-on: ubuntu-latest
    steps:
    - name: Run command on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.HOST_USER}}
        key: ${{secrets.HOST_KEY}}
        script: |
          export NVM_DIR="$HOME/.nvm";
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion";
          nvm use 18
          cd ${{ secrets.PROJECT_FOLDER_DEV }};
          git checkout main;
          git pull;
          git add .
          git commit -m 'Added content types';
          npm version patch;
          git push origin main;
          echo "APP_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')" > app-version.env;
          docker rmi $(docker images --filter "reference=culture-portal-cusco-admin-dev*" -q);
          docker compose --env-file app-version.env --env-file .env -f docker-compose.dev.yml up --detach;
          echo '--- UPDATE PROD ---'
          cd ${{ secrets.PROJECT_FOLDER_PROD }};
          git checkout main;
          git pull;
          echo "APP_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')" > app-version.env;
          docker rmi $(docker images --filter "reference=culture-portal-cusco-admin-prod*" -q);
          docker compose --env-file app-version.env --env-file .env -f docker-compose.prod.yml up --detach;